export const INITIAL_USERS = [
  {
    id: 'u-teacher-1',
    name: 'Mrs. Sarah Davis',
    email: 'davis@elementary.edu',
    role: 'teacher',
    is_pro: true,
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    class_name: 'Grade 3 - Room 2B',
  },
  {
    id: 'u-student-1',
    name: 'Leo Martinez',
    email: 'leo.m@student.edu',
    role: 'student',
    is_pro: false,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    class_name: 'Grade 3 - Room 2B',
  },
  {
    id: 'u-student-2',
    name: 'Sophia Chen',
    email: 'sophia.c@student.edu',
    role: 'student',
    is_pro: false,
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    class_name: 'Grade 3 - Room 2B',
  },
  {
    id: 'u-parent-1',
    name: 'David Martinez',
    email: 'david.martinez@gmail.com',
    role: 'parent',
    is_pro: false,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    class_name: null,
  },
];

export const INITIAL_GAMES = [
  {
    id: 'g-1',
    name: 'Wheel Spin',
    slug: 'wheel-spin',
    description: 'Spin a colorful prize wheel to select questions, win points, and clear challenges!',
    mechanic: 'Wheel Spin + Question Quiz',
    badge: 'Popular',
    category: 'arcade',
    min_grade: 'K - 8',
    icon_name: 'PieChart',
    gradient_bg: 'from-amber-500 to-rose-500',
    accent_color: '#f59e0b',
    image_url: '/assets/images/wheel_spin_game_1785564142771.jpg',
  },
  {
    id: 'g-2',
    name: 'Ship Battle',
    slug: 'ship-battle',
    description: 'Command a pirate ship! Fire naval cannons at enemy vessels by answering questions correctly.',
    mechanic: 'Action Battle + Strategy',
    badge: 'Action',
    category: 'arcade',
    min_grade: '1 - 8',
    icon_name: 'Ship',
    gradient_bg: 'from-blue-600 to-indigo-700',
    accent_color: '#2563eb',
    image_url: '/assets/images/ship_battle_game_1785564155376.jpg',
  },
  {
    id: 'g-3',
    name: 'Alien Spelling',
    slug: 'alien-spelling',
    description: 'Help friendly alien astronauts decode cosmic word signals and spell target vocab words!',
    mechanic: 'Spelling & Phonics',
    badge: 'Phonics',
    category: 'slp',
    min_grade: 'K - 5',
    icon_name: 'Rocket',
    gradient_bg: 'from-purple-600 to-pink-600',
    accent_color: '#9333ea',
    image_url: '/assets/images/alien_spelling_game_1785564167746.jpg',
  },
  {
    id: 'g-4',
    name: 'Crane Game',
    slug: 'crane-game',
    description: 'Operate an arcade claw machine! Lower the claw to lift surprise reward boxes with right answers.',
    mechanic: 'Arcade Physics',
    badge: 'Fun',
    category: 'arcade',
    min_grade: 'K - 6',
    icon_name: 'Box',
    gradient_bg: 'from-emerald-500 to-teal-700',
    accent_color: '#10b981',
    image_url: '/assets/images/crane_game_cover_1785564180477.jpg',
  },
  {
    id: 'g-5',
    name: 'Magic Potions',
    slug: 'magic-potions',
    description: 'Combine magical ingredients in a bubbling cauldron and transform magical creatures!',
    mechanic: 'Matching & Sequencing',
    badge: 'Creative',
    category: 'puzzle',
    min_grade: 'K - 5',
    icon_name: 'Sparkles',
    gradient_bg: 'from-violet-600 to-fuchsia-600',
    accent_color: '#7c3aed',
    image_url: '/assets/images/magic_potions_game_1785564196384.jpg',
  },
  {
    id: 'g-6',
    name: 'Flashcards',
    slug: 'flashcards',
    description: 'Flip 3D cards, self-mark known vs unknown terms, and master vocabulary with spaced repetition.',
    mechanic: 'Spaced Repetition Study',
    badge: 'Study Tool',
    category: 'quiz',
    min_grade: 'All Grades',
    icon_name: 'Layers',
    gradient_bg: 'from-sky-500 to-blue-600',
    accent_color: '#0284c7',
    image_url: '/assets/images/flashcards_game_1785564211020.jpg',
  },
  {
    id: 'g-7',
    name: 'Roll & Read',
    slug: 'roll-and-read',
    description: 'Roll 3D dice to pick questions or articulation targets to read aloud with built-in TTS assistance!',
    mechanic: 'SLP & Phonics Reading',
    badge: 'SLP Favorite',
    category: 'slp',
    min_grade: 'PreK - 6',
    icon_name: 'Dices',
    gradient_bg: 'from-orange-500 to-amber-600',
    accent_color: '#ea580c',
    image_url: '/assets/images/roll_and_read_game_1785564222038.jpg',
  },
  {
    id: 'g-8',
    name: 'Ocean Quest',
    slug: 'ocean-quest',
    description: 'Submerge into deep waters! Dive down to unlock glowing sunken treasure chests on the ocean floor.',
    mechanic: 'Exploration & Collection',
    badge: 'Adventure',
    category: 'arcade',
    min_grade: '1 - 6',
    icon_name: 'Waves',
    gradient_bg: 'from-cyan-600 to-blue-800',
    accent_color: '#0891b2',
    image_url: '/assets/images/ocean_quest_game_1785564235278.jpg',
  },
];

export const INITIAL_QUESTION_SETS = [
  {
    id: 'qs-1',
    ownerId: 'u-teacher-1',
    ownerName: 'Mrs. Sarah Davis',
    title: 'Sight Words & Early Phonics',
    description: 'Essential high-frequency sight words and phonetic vowel sounds for early readers.',
    subject: 'Reading & Phonics',
    gradeLevel: 'Grade 1 - 2',
    isPublic: true,
    tags: JSON.stringify(['sight-words', 'phonics', 'reading', 'slp']),
    createdAt: '2026-07-15 10:00:00',
    updatedAt: '2026-07-20 14:30:00',
    questions: [
      { id: 'q1-1', set_id: 'qs-1', promptText: 'Which word means "at the present time"?', answer: 'NOW', options: JSON.stringify(['NOW', 'HOW', 'COW', 'BOW']), type: 'multiple_choice', position: 1, hint: 'Rhymes with cow' },
      { id: 'q1-2', set_id: 'qs-1', promptText: 'What is the opposite of "BEFORE"?', answer: 'AFTER', options: JSON.stringify(['AFTER', 'UNDER', 'OVER', 'NEVER']), type: 'multiple_choice', position: 2, hint: 'Starts with letter A' },
      { id: 'q1-3', set_id: 'qs-1', promptText: 'Read and spell the word for a shining star in the sky.', answer: 'BRIGHT', options: JSON.stringify(['BRIGHT', 'LIGHT', 'NIGHT', 'FLIGHT']), type: 'multiple_choice', position: 3 },
      { id: 'q1-4', set_id: 'qs-1', promptText: 'Complete the sentence: "The birds fly high in the ______."', answer: 'SKY', options: JSON.stringify(['SKY', 'TRY', 'DRY', 'FLY']), type: 'multiple_choice', position: 4 },
      { id: 'q1-5', set_id: 'qs-1', promptText: 'Which word rhymes with "BEACH"?', answer: 'PEACH', options: JSON.stringify(['PEACH', 'REACH', 'TEACH', 'ALL OF THESE']), type: 'multiple_choice', position: 5 },
      { id: 'q1-6', set_id: 'qs-1', promptText: 'Which word means to move quickly on foot?', answer: 'RUN', options: JSON.stringify(['RUN', 'SUN', 'FUN', 'BUN']), type: 'multiple_choice', position: 6, hint: 'What you do in a race' },
      { id: 'q1-7', set_id: 'qs-1', promptText: 'Complete: "I can ___ the ball very far."', answer: 'THROW', options: JSON.stringify(['THROW', 'SHOW', 'FLOW', 'SNOW']), type: 'multiple_choice', position: 7 },
      { id: 'q1-8', set_id: 'qs-1', promptText: 'Which word describes the color of the sun?', answer: 'YELLOW', options: JSON.stringify(['YELLOW', 'MELLOW', 'FELLOW', 'BELOW']), type: 'multiple_choice', position: 8 },
      { id: 'q1-9', set_id: 'qs-1', promptText: 'Which word is the plural of "child"?', answer: 'CHILDREN', options: JSON.stringify(['CHILDS', 'CHILDEN', 'CHILDREN', 'CHILDRENS']), type: 'multiple_choice', position: 9, hint: 'Irregular plural form' },
      { id: 'q1-10', set_id: 'qs-1', promptText: 'What letter does the word "ELEPHANT" start with?', answer: 'E', options: JSON.stringify(['A', 'E', 'I', 'O']), type: 'multiple_choice', position: 10 },
      { id: 'q1-11', set_id: 'qs-1', promptText: 'Which word means to look at something for a long time?', answer: 'STARE', options: JSON.stringify(['SHARE', 'STARE', 'SPARE', 'FLARE']), type: 'multiple_choice', position: 11 },
      { id: 'q1-12', set_id: 'qs-1', promptText: 'Complete: "She ___ her homework every night."', answer: 'DOES', options: JSON.stringify(['DOSE', 'DOES', 'DOOS', 'DOSS']), type: 'multiple_choice', position: 12 },
      { id: 'q1-13', set_id: 'qs-1', promptText: 'What vowel sound is in the word "BITE"?', answer: 'Long I', options: JSON.stringify(['Short A', 'Long I', 'Short E', 'Long U']), type: 'multiple_choice', position: 13, hint: 'The I makes its name sound' },
      { id: 'q1-14', set_id: 'qs-1', promptText: 'Which word is spelled correctly?', answer: 'BECAUSE', options: JSON.stringify(['BECUASE', 'BECAUSE', 'BECUSE', 'BECAUS']), type: 'multiple_choice', position: 14 },
      { id: 'q1-15', set_id: 'qs-1', promptText: 'Which word is a sight word that means "every person"?', answer: 'EVERYONE', options: JSON.stringify(['EVERYONE', 'EVRYONE', 'EVERYON', 'EVREYONE']), type: 'multiple_choice', position: 15 },
    ],
  },
  {
    id: 'qs-2',
    ownerId: 'u-teacher-1',
    ownerName: 'Mrs. Sarah Davis',
    title: 'Math Safari: Addition & Multiplication',
    description: 'Fun arithmetic mental math challenges featuring wild safari animals.',
    subject: 'Mathematics',
    gradeLevel: 'Grade 2 - 4',
    isPublic: true,
    tags: JSON.stringify(['math', 'addition', 'multiplication', 'mental-math']),
    createdAt: '2026-07-18 11:20:00',
    updatedAt: '2026-07-22 09:15:00',
    questions: [
      { id: 'q2-1', set_id: 'qs-2', promptText: 'What is 7 + 8?', answer: '15', options: JSON.stringify(['13', '14', '15', '16']), type: 'multiple_choice', position: 1 },
      { id: 'q2-2', set_id: 'qs-2', promptText: 'What is 6 × 4?', answer: '24', options: JSON.stringify(['20', '24', '28', '30']), type: 'multiple_choice', position: 2 },
      { id: 'q2-3', set_id: 'qs-2', promptText: 'A cheetah runs 12 miles in the morning and 15 miles in the afternoon. Total miles?', answer: '27', options: JSON.stringify(['25', '27', '29', '31']), type: 'multiple_choice', position: 3 },
      { id: 'q2-4', set_id: 'qs-2', promptText: 'What is 9 × 3?', answer: '27', options: JSON.stringify(['24', '27', '30', '36']), type: 'multiple_choice', position: 4 },
      { id: 'q2-5', set_id: 'qs-2', promptText: 'What is 45 ÷ 5?', answer: '9', options: JSON.stringify(['7', '8', '9', '10']), type: 'multiple_choice', position: 5 },
      { id: 'q2-6', set_id: 'qs-2', promptText: 'What is 13 + 19?', answer: '32', options: JSON.stringify(['30', '31', '32', '33']), type: 'multiple_choice', position: 6 },
      { id: 'q2-7', set_id: 'qs-2', promptText: 'What is 8 × 7?', answer: '56', options: JSON.stringify(['48', '54', '56', '64']), type: 'multiple_choice', position: 7 },
      { id: 'q2-8', set_id: 'qs-2', promptText: 'What is 72 ÷ 8?', answer: '9', options: JSON.stringify(['7', '8', '9', '10']), type: 'multiple_choice', position: 8 },
      { id: 'q2-9', set_id: 'qs-2', promptText: 'A lion has 4 legs. How many legs do 6 lions have?', answer: '24', options: JSON.stringify(['20', '22', '24', '28']), type: 'multiple_choice', position: 9, hint: '4 × 6' },
      { id: 'q2-10', set_id: 'qs-2', promptText: 'What is 100 - 37?', answer: '63', options: JSON.stringify(['63', '67', '73', '57']), type: 'multiple_choice', position: 10 },
      { id: 'q2-11', set_id: 'qs-2', promptText: 'What is 5 × 12?', answer: '60', options: JSON.stringify(['50', '55', '60', '65']), type: 'multiple_choice', position: 11 },
      { id: 'q2-12', set_id: 'qs-2', promptText: 'What is 48 ÷ 6?', answer: '8', options: JSON.stringify(['6', '7', '8', '9']), type: 'multiple_choice', position: 12 },
      { id: 'q2-13', set_id: 'qs-2', promptText: 'What is 25 + 38?', answer: '63', options: JSON.stringify(['61', '62', '63', '64']), type: 'multiple_choice', position: 13 },
      { id: 'q2-14', set_id: 'qs-2', promptText: 'What is 11 × 11?', answer: '121', options: JSON.stringify(['111', '121', '131', '122']), type: 'multiple_choice', position: 14 },
      { id: 'q2-15', set_id: 'qs-2', promptText: 'There are 3 giraffes with 4 spots each. Total spots?', answer: '12', options: JSON.stringify(['10', '11', '12', '14']), type: 'multiple_choice', position: 15, hint: '3 × 4' },
    ],
  },
  {
    id: 'qs-3',
    ownerId: 'u-teacher-1',
    ownerName: 'Mrs. Sarah Davis',
    title: 'SLP Articulation: "R" & "S" Sound Drills',
    description: 'Targeted speech-language therapy word list for speech clarity and articulation drills.',
    subject: 'Speech Therapy (SLP)',
    gradeLevel: 'All Grades',
    isPublic: true,
    tags: JSON.stringify(['slp', 'speech-therapy', 'articulation', 'phonics']),
    createdAt: '2026-07-20 08:00:00',
    updatedAt: '2026-07-25 16:00:00',
    questions: [
      { id: 'q3-1', set_id: 'qs-3', promptText: 'Pronounce aloud: "RED ROCKET"', answer: 'RED ROCKET', options: JSON.stringify(['RED ROCKET', 'BED LOCKET', 'WED WOCKET', 'RED LOCKET']), type: 'text', position: 1, hint: 'Keep tongue tip curved back for initial R' },
      { id: 'q3-2', set_id: 'qs-3', promptText: 'Pronounce aloud: "SUPER SUNSHINE"', answer: 'SUPER SUNSHINE', options: JSON.stringify(['SUPER SUNSHINE', 'SHUPER SUNSHINE', 'THUPER THUNTHINE', 'SOUPER SUNSET']), type: 'text', position: 2, hint: 'Light smile position, tongue behind front teeth for S' },
      { id: 'q3-3', set_id: 'qs-3', promptText: 'Spell and say: "RABBIT RUNS FAST"', answer: 'RABBIT', options: JSON.stringify(['RABBIT', 'RIVER', 'ROBOT', 'RING']), type: 'multiple_choice', position: 3 },
      { id: 'q3-4', set_id: 'qs-3', promptText: 'Say out loud: "STARLIGHT SPARKLE"', answer: 'SPARKLE', options: JSON.stringify(['SPARKLE', 'SILVER', 'SMILE', 'SPIDER']), type: 'multiple_choice', position: 4 },
      { id: 'q3-5', set_id: 'qs-3', promptText: 'Articulation blend: "STRAWBERRY RAIN"', answer: 'STRAWBERRY', options: JSON.stringify(['STRAWBERRY', 'RASPBERRY', 'BLUEBERRY', 'CHERRY']), type: 'multiple_choice', position: 5 },
      { id: 'q3-6', set_id: 'qs-3', promptText: 'Say the word for the season when it snows.', answer: 'WINTER', options: JSON.stringify(['WINNER', 'WINTER', 'WINDER', 'WINDER']), type: 'multiple_choice', position: 6, hint: 'Starts with W-IN-T-ER' },
      { id: 'q3-7', set_id: 'qs-3', promptText: 'Pronounce: "ROUND RED RADISHES"', answer: 'ROUND RED RADISHES', options: JSON.stringify(['ROUND RED RADISHES', 'WOUND WED WADISHES', 'BOUND RED RADISHES', 'ROUND BED BADISHES']), type: 'text', position: 7, hint: 'Practice the initial R sound clearly' },
      { id: 'q3-8', set_id: 'qs-3', promptText: 'Which word has the /s/ sound at the start?', answer: 'SNAKE', options: JSON.stringify(['CHAIR', 'SNAKE', 'PHONE', 'WHALE']), type: 'multiple_choice', position: 8 },
      { id: 'q3-9', set_id: 'qs-3', promptText: 'Say the sentence: "Sara sees seven stars."', answer: 'SARA SEES SEVEN STARS', options: JSON.stringify(['SARA SEES SEVEN STARS', 'THARA THEETH THEVEN', 'SARA SEEZ SEVEN STARZ', 'ZARA ZEEZ ZEVEN']), type: 'text', position: 9, hint: 'All words start with /s/' },
      { id: 'q3-10', set_id: 'qs-3', promptText: 'Which word has the /r/ blend at the start?', answer: 'FROG', options: JSON.stringify(['FLAG', 'FROG', 'FLIP', 'FLAT']), type: 'multiple_choice', position: 10 },
      { id: 'q3-11', set_id: 'qs-3', promptText: 'Speak aloud: "River Runs Rapidly."', answer: 'RIVER', options: JSON.stringify(['RIVER', 'LIVER', 'GIVER', 'SILVER']), type: 'multiple_choice', position: 11, hint: 'Voiced R at start' },
      { id: 'q3-12', set_id: 'qs-3', promptText: 'Which word has the /s/ sound in the middle?', answer: 'LISTEN', options: JSON.stringify(['BUTTON', 'LISTEN', 'KITTEN', 'BITTEN']), type: 'multiple_choice', position: 12 },
      { id: 'q3-13', set_id: 'qs-3', promptText: 'Pronounce: "SPRING SPROUTS"', answer: 'SPRING SPROUTS', options: JSON.stringify(['SPRING SPROUTS', 'PRING PROUTS', 'THPRING THPROUTS', 'SPING SPOUT']), type: 'text', position: 13, hint: 'Blend the /spr/ cluster' },
      { id: 'q3-14', set_id: 'qs-3', promptText: 'What is the animal that says "ROAR"?', answer: 'LION', options: JSON.stringify(['LION', 'LOIN', 'LIEN', 'LINE']), type: 'multiple_choice', position: 14 },
      { id: 'q3-15', set_id: 'qs-3', promptText: 'Say: "SILLY SALLY SINGS SOFTLY"', answer: 'SILLY SALLY SINGS SOFTLY', options: JSON.stringify(['SILLY SALLY SINGS SOFTLY', 'THILLY THALLY THINGTH', 'ZILLY ZALLY ZINGZ', 'SILLY SALY SINGZ SOFTLY']), type: 'text', position: 15, hint: 'Focus on clear /s/ sounds' },
    ],
  },
  {
    id: 'qs-4',
    ownerId: 'u-teacher-1',
    ownerName: 'Mrs. Sarah Davis',
    title: 'World Capitals & Geography',
    description: 'Identify countries, continents, and capital cities from around the globe.',
    subject: 'Social Studies',
    gradeLevel: 'Grade 3 - 6',
    isPublic: true,
    tags: JSON.stringify(['geography', 'capitals', 'world', 'social-studies']),
    createdAt: '2026-07-22 14:10:00',
    updatedAt: '2026-07-28 11:00:00',
    questions: [
      { id: 'q4-1', set_id: 'qs-4', promptText: 'What is the capital city of France?', answer: 'PARIS', options: JSON.stringify(['PARIS', 'LYON', 'MARSEILLE', 'NICE']), type: 'multiple_choice', position: 1 },
      { id: 'q4-2', set_id: 'qs-4', promptText: 'What is the capital city of Japan?', answer: 'TOKYO', options: JSON.stringify(['KYOTO', 'OSAKA', 'TOKYO', 'SAPPORO']), type: 'multiple_choice', position: 2 },
      { id: 'q4-3', set_id: 'qs-4', promptText: 'Which continent is home to the Amazon Rainforest?', answer: 'SOUTH AMERICA', options: JSON.stringify(['AFRICA', 'SOUTH AMERICA', 'ASIA', 'OCEANIA']), type: 'multiple_choice', position: 3 },
      { id: 'q4-4', set_id: 'qs-4', promptText: 'What is the largest ocean on Earth?', answer: 'PACIFIC OCEAN', options: JSON.stringify(['ATLANTIC OCEAN', 'INDIAN OCEAN', 'PACIFIC OCEAN', 'ARCTIC OCEAN']), type: 'multiple_choice', position: 4 },
      { id: 'q4-5', set_id: 'qs-4', promptText: 'What is the capital city of Canada?', answer: 'OTTAWA', options: JSON.stringify(['TORONTO', 'VANCOUVER', 'MONTREAL', 'OTTAWA']), type: 'multiple_choice', position: 5 },
      { id: 'q4-6', set_id: 'qs-4', promptText: 'What is the capital city of Australia?', answer: 'CANBERRA', options: JSON.stringify(['SYDNEY', 'MELBOURNE', 'CANBERRA', 'BRISBANE']), type: 'multiple_choice', position: 6 },
      { id: 'q4-7', set_id: 'qs-4', promptText: 'Which country is the largest in the world by area?', answer: 'RUSSIA', options: JSON.stringify(['CHINA', 'USA', 'CANADA', 'RUSSIA']), type: 'multiple_choice', position: 7 },
      { id: 'q4-8', set_id: 'qs-4', promptText: 'What is the capital city of Brazil?', answer: 'BRASILIA', options: JSON.stringify(['RIO DE JANEIRO', 'SAO PAULO', 'BRASILIA', 'SALVADOR']), type: 'multiple_choice', position: 8 },
      { id: 'q4-9', set_id: 'qs-4', promptText: 'On which continent is the Sahara Desert located?', answer: 'AFRICA', options: JSON.stringify(['ASIA', 'AFRICA', 'SOUTH AMERICA', 'AUSTRALIA']), type: 'multiple_choice', position: 9 },
      { id: 'q4-10', set_id: 'qs-4', promptText: 'What is the capital of Germany?', answer: 'BERLIN', options: JSON.stringify(['MUNICH', 'FRANKFURT', 'BERLIN', 'HAMBURG']), type: 'multiple_choice', position: 10 },
      { id: 'q4-11', set_id: 'qs-4', promptText: 'How many continents are there on Earth?', answer: '7', options: JSON.stringify(['5', '6', '7', '8']), type: 'multiple_choice', position: 11 },
      { id: 'q4-12', set_id: 'qs-4', promptText: 'What is the capital of the Philippines?', answer: 'MANILA', options: JSON.stringify(['CEBU', 'DAVAO', 'MANILA', 'QUEZON CITY']), type: 'multiple_choice', position: 12 },
      { id: 'q4-13', set_id: 'qs-4', promptText: 'What is the tallest mountain in the world?', answer: 'MOUNT EVEREST', options: JSON.stringify(['MOUNT KILIMANJARO', 'MOUNT EVEREST', 'MOUNT FUJI', 'MOUNT BLANC']), type: 'multiple_choice', position: 13 },
      { id: 'q4-14', set_id: 'qs-4', promptText: 'Which river is the longest in the world?', answer: 'NILE', options: JSON.stringify(['AMAZON', 'NILE', 'YANGTZE', 'MISSISSIPPI']), type: 'multiple_choice', position: 14 },
      { id: 'q4-15', set_id: 'qs-4', promptText: 'What is the capital city of India?', answer: 'NEW DELHI', options: JSON.stringify(['MUMBAI', 'KOLKATA', 'NEW DELHI', 'BANGALORE']), type: 'multiple_choice', position: 15 },
    ],
  },
  {
    id: 'qs-5',
    ownerId: 'u-teacher-1',
    ownerName: 'Mrs. Sarah Davis',
    title: 'Elementary Science: Planets & Animals',
    description: 'Explore the solar system, animal habitats, and plant lifecycles.',
    subject: 'Science',
    gradeLevel: 'Grade 2 - 5',
    isPublic: true,
    tags: JSON.stringify(['science', 'planets', 'animals', 'space']),
    createdAt: '2026-07-24 09:30:00',
    updatedAt: '2026-07-29 10:15:00',
    questions: [
      { id: 'q5-1', set_id: 'qs-5', promptText: 'Which planet is known as the Red Planet?', answer: 'MARS', options: JSON.stringify(['VENUS', 'MARS', 'JUPITER', 'SATURN']), type: 'multiple_choice', position: 1 },
      { id: 'q5-2', set_id: 'qs-5', promptText: 'What process do green plants use to convert sunlight into food?', answer: 'PHOTOSYNTHESIS', options: JSON.stringify(['PHOTOSYNTHESIS', 'RESPIRATION', 'EVAPORATION', 'FERMENTATION']), type: 'multiple_choice', position: 2 },
      { id: 'q5-3', set_id: 'qs-5', promptText: 'Which mammal is capable of true flight?', answer: 'BAT', options: JSON.stringify(['FLYING SQUIRREL', 'BAT', 'PENGUIN', 'OWL']), type: 'multiple_choice', position: 3 },
      { id: 'q5-4', set_id: 'qs-5', promptText: 'What is the largest planet in our Solar System?', answer: 'JUPITER', options: JSON.stringify(['EARTH', 'NEPTUNE', 'SATURN', 'JUPITER']), type: 'multiple_choice', position: 4 },
      { id: 'q5-5', set_id: 'qs-5', promptText: 'How many planets are in our Solar System?', answer: '8', options: JSON.stringify(['7', '8', '9', '10']), type: 'multiple_choice', position: 5 },
      { id: 'q5-6', set_id: 'qs-5', promptText: 'What is the closest star to Earth?', answer: 'SUN', options: JSON.stringify(['SIRIUS', 'POLARIS', 'SUN', 'PROXIMA CENTAURI']), type: 'multiple_choice', position: 6 },
      { id: 'q5-7', set_id: 'qs-5', promptText: 'What animal is called the "King of the Jungle"?', answer: 'LION', options: JSON.stringify(['TIGER', 'LION', 'ELEPHANT', 'GORILLA']), type: 'multiple_choice', position: 7 },
      { id: 'q5-8', set_id: 'qs-5', promptText: 'Which planet has rings made of ice and rock?', answer: 'SATURN', options: JSON.stringify(['URANUS', 'NEPTUNE', 'SATURN', 'JUPITER']), type: 'multiple_choice', position: 8 },
      { id: 'q5-9', set_id: 'qs-5', promptText: 'What do caterpillars transform into?', answer: 'BUTTERFLY', options: JSON.stringify(['MOTH', 'BUTTERFLY', 'BEE', 'DRAGONFLY']), type: 'multiple_choice', position: 9, hint: 'It has colorful wings' },
      { id: 'q5-10', set_id: 'qs-5', promptText: 'What is the smallest planet in our Solar System?', answer: 'MERCURY', options: JSON.stringify(['MARS', 'VENUS', 'MERCURY', 'PLUTO']), type: 'multiple_choice', position: 10 },
      { id: 'q5-11', set_id: 'qs-5', promptText: 'What is a group of lions called?', answer: 'PRIDE', options: JSON.stringify(['PACK', 'PRIDE', 'HERD', 'FLOCK']), type: 'multiple_choice', position: 11 },
      { id: 'q5-12', set_id: 'qs-5', promptText: 'Which animal has the longest neck?', answer: 'GIRAFFE', options: JSON.stringify(['OSTRICH', 'FLAMINGO', 'GIRAFFE', 'CAMEL']), type: 'multiple_choice', position: 12 },
      { id: 'q5-13', set_id: 'qs-5', promptText: 'What force pulls objects toward Earth?', answer: 'GRAVITY', options: JSON.stringify(['MAGNETISM', 'FRICTION', 'GRAVITY', 'INERTIA']), type: 'multiple_choice', position: 13 },
      { id: 'q5-14', set_id: 'qs-5', promptText: 'What planet do we live on?', answer: 'EARTH', options: JSON.stringify(['MARS', 'VENUS', 'EARTH', 'SATURN']), type: 'multiple_choice', position: 14 },
      { id: 'q5-15', set_id: 'qs-5', promptText: 'What do plants need to make food through photosynthesis?', answer: 'SUNLIGHT, WATER, AND CO2', options: JSON.stringify(['SUNLIGHT, WATER, AND CO2', 'SOIL, RAIN, AND WIND', 'OXYGEN, SOIL, AND SUN', 'WATER, OXYGEN, AND SOIL']), type: 'multiple_choice', position: 15, hint: 'Three ingredients for food-making' },
    ],
  },
  {
    id: "qs-6",
    owner_id: "u-teacher-1",
    owner_name: "Mrs. Sarah Davis",
    title: "Basic Algebra Masterclass (35 Items)",
    description: "Comprehensive algebra practice covering linear equations, variables, exponents, and expression simplification.",
    subject: "Mathematics",
    grade_level: "Grade 5 - 8",
    is_public: true,
    tags: JSON.stringify(["algebra","math","equations","variables","mastery"]),
    created_at: '2026-08-01 08:00:00',
    updated_at: '2026-08-05 12:00:00',
    questions: [
      {
        id: "qs-6-q1",
        set_id: "qs-6",
        prompt_text: "Solve for x: x + 7 = 15",
        answer: "8",
        options: JSON.stringify(["6","7","8","9"]),
        type: 'multiple_choice',
        position: 1,
        hint: "Subtract 7 from both sides"
      },
      {
        id: "qs-6-q2",
        set_id: "qs-6",
        prompt_text: "Solve for x: 3x = 21",
        answer: "7",
        options: JSON.stringify(["5","6","7","8"]),
        type: 'multiple_choice',
        position: 2,
        hint: "Divide both sides by 3"
      },
      {
        id: "qs-6-q3",
        set_id: "qs-6",
        prompt_text: "Solve for y: 2y - 4 = 10",
        answer: "7",
        options: JSON.stringify(["5","6","7","8"]),
        type: 'multiple_choice',
        position: 3,
        hint: "Add 4 then divide by 2"
      },
      {
        id: "qs-6-q4",
        set_id: "qs-6",
        prompt_text: "What is the value of 5x when x = 4?",
        answer: "20",
        options: JSON.stringify(["15","20","25","30"]),
        type: 'multiple_choice',
        position: 4,
        hint: "Multiply 5 by 4"
      },
      {
        id: "qs-6-q5",
        set_id: "qs-6",
        prompt_text: "Simplify: 4a + 3a",
        answer: "7a",
        options: JSON.stringify(["7a","12a","7a²","12"]),
        type: 'multiple_choice',
        position: 5,
        hint: "Add the coefficients 4 + 3"
      },
      {
        id: "qs-6-q6",
        set_id: "qs-6",
        prompt_text: "Solve for m: m / 4 = 6",
        answer: "24",
        options: JSON.stringify(["10","20","24","28"]),
        type: 'multiple_choice',
        position: 6,
        hint: "Multiply 6 by 4"
      },
      {
        id: "qs-6-q7",
        set_id: "qs-6",
        prompt_text: "Evaluate: 2³ (2 to the power of 3)",
        answer: "8",
        options: JSON.stringify(["6","8","9","16"]),
        type: 'multiple_choice',
        position: 7,
        hint: "2 * 2 * 2"
      },
      {
        id: "qs-6-q8",
        set_id: "qs-6",
        prompt_text: "Solve for n: n + 12 = 30",
        answer: "18",
        options: JSON.stringify(["16","18","20","22"]),
        type: 'multiple_choice',
        position: 8,
        hint: "Subtract 12 from 30"
      },
      {
        id: "qs-6-q9",
        set_id: "qs-6",
        prompt_text: "What is the coefficient of x in the term 9x?",
        answer: "9",
        options: JSON.stringify(["x","9","1","9x"]),
        type: 'multiple_choice',
        position: 9,
        hint: "The number multiplying x"
      },
      {
        id: "qs-6-q10",
        set_id: "qs-6",
        prompt_text: "Solve for x: 5x + 3 = 28",
        answer: "5",
        options: JSON.stringify(["4","5","6","7"]),
        type: 'multiple_choice',
        position: 10,
        hint: "5x = 25"
      },
      {
        id: "qs-6-q11",
        set_id: "qs-6",
        prompt_text: "Simplify: 9y - 4y + 2y",
        answer: "7y",
        options: JSON.stringify(["5y","7y","11y","7"]),
        type: 'multiple_choice',
        position: 11,
        hint: "(9 - 4 + 2)y"
      },
      {
        id: "qs-6-q12",
        set_id: "qs-6",
        prompt_text: "If p = 3 and q = 4, what is p * q + 2?",
        answer: "14",
        options: JSON.stringify(["12","14","16","18"]),
        type: 'multiple_choice',
        position: 12,
        hint: "3 * 4 + 2"
      },
      {
        id: "qs-6-q13",
        set_id: "qs-6",
        prompt_text: "Solve for x: 4x = 32",
        answer: "8",
        options: JSON.stringify(["6","7","8","9"]),
        type: 'multiple_choice',
        position: 13,
        hint: "32 / 4"
      },
      {
        id: "qs-6-q14",
        set_id: "qs-6",
        prompt_text: "Which expression represents \"5 more than a number n\"?",
        answer: "n + 5",
        options: JSON.stringify(["n + 5","5n","n - 5","5 / n"]),
        type: 'multiple_choice',
        position: 14
      },
      {
        id: "qs-6-q15",
        set_id: "qs-6",
        prompt_text: "Solve for k: k - 9 = 15",
        answer: "24",
        options: JSON.stringify(["21","22","24","26"]),
        type: 'multiple_choice',
        position: 15,
        hint: "15 + 9"
      },
    ],
  },
  {
    id: "qs-7",
    owner_id: "u-teacher-1",
    owner_name: "Mrs. Sarah Davis",
    title: "Human Body & Anatomy Science (15 Items)",
    description: "Explore human body systems including bones, organs, muscles, blood circulation, and brain functions.",
    subject: "Science",
    grade_level: "Grade 4 - 8",
    is_public: true,
    tags: JSON.stringify(["science","anatomy","human-body","biology","organs"]),
    created_at: '2026-08-01 08:00:00',
    updated_at: '2026-08-05 12:00:00',
    questions: [
      {
        id: "qs-7-q1",
        set_id: "qs-7",
        prompt_text: "How many bones are in the adult human body?",
        answer: "206",
        options: JSON.stringify(["150","206","300","350"]),
        type: 'multiple_choice',
        position: 1
      },
      {
        id: "qs-7-q2",
        set_id: "qs-7",
        prompt_text: "Which organ pumps blood throughout the body?",
        answer: "HEART",
        options: JSON.stringify(["LUNGS","HEART","LIVER","BRAIN"]),
        type: 'multiple_choice',
        position: 2
      },
      {
        id: "qs-7-q3",
        set_id: "qs-7",
        prompt_text: "What is the main gas absorbed by lungs during inhalation?",
        answer: "OXYGEN",
        options: JSON.stringify(["CARBON DIOXIDE","NITROGEN","OXYGEN","HYDROGEN"]),
        type: 'multiple_choice',
        position: 3
      },
      {
        id: "qs-7-q4",
        set_id: "qs-7",
        prompt_text: "Which organ controls thought, memory, and emotion?",
        answer: "BRAIN",
        options: JSON.stringify(["HEART","BRAIN","STOMACH","SPINE"]),
        type: 'multiple_choice',
        position: 4
      },
      {
        id: "qs-7-q5",
        set_id: "qs-7",
        prompt_text: "What is the hardest substance in the human body?",
        answer: "TOOTH ENAMEL",
        options: JSON.stringify(["BONE","TOOTH ENAMEL","CARTILAGE","SKULL"]),
        type: 'multiple_choice',
        position: 5
      },
      {
        id: "qs-7-q6",
        set_id: "qs-7",
        prompt_text: "Which body system helps defend against germs and infections?",
        answer: "IMMUNE SYSTEM",
        options: JSON.stringify(["DIGESTIVE SYSTEM","IMMUNE SYSTEM","SKELETAL SYSTEM","MUSCULAR SYSTEM"]),
        type: 'multiple_choice',
        position: 6
      },
      {
        id: "qs-7-q7",
        set_id: "qs-7",
        prompt_text: "Where does most food digestion and nutrient absorption occur?",
        answer: "SMALL INTESTINE",
        options: JSON.stringify(["STOMACH","SMALL INTESTINE","LARGE INTESTINE","ESOPHAGUS"]),
        type: 'multiple_choice',
        position: 7
      },
      {
        id: "qs-7-q8",
        set_id: "qs-7",
        prompt_text: "What carries oxygenated blood away from the heart?",
        answer: "ARTERIES",
        options: JSON.stringify(["VEINS","ARTERIES","CAPILLARIES","NERVES"]),
        type: 'multiple_choice',
        position: 8
      },
      {
        id: "qs-7-q9",
        set_id: "qs-7",
        prompt_text: "Which pigment gives human skin and hair its color?",
        answer: "MELANIN",
        options: JSON.stringify(["KERATIN","MELANIN","HEMOGLOBIN","CAROTENE"]),
        type: 'multiple_choice',
        position: 9
      },
      {
        id: "qs-7-q10",
        set_id: "qs-7",
        prompt_text: "How many chambers does the human heart have?",
        answer: "4",
        options: JSON.stringify(["2","3","4","6"]),
        type: 'multiple_choice',
        position: 10
      },
      {
        id: "qs-7-q11",
        set_id: "qs-7",
        prompt_text: "What type of joint is found at the shoulder and hip?",
        answer: "BALL AND SOCKET",
        options: JSON.stringify(["HINGE","BALL AND SOCKET","PIVOT","FIXED"]),
        type: 'multiple_choice',
        position: 11
      },
      {
        id: "qs-7-q12",
        set_id: "qs-7",
        prompt_text: "Which organ filters waste products from blood to produce urine?",
        answer: "KIDNEYS",
        options: JSON.stringify(["LIVER","KIDNEYS","SPLEEN","PANCREAS"]),
        type: 'multiple_choice',
        position: 12
      },
      {
        id: "qs-7-q13",
        set_id: "qs-7",
        prompt_text: "What protein in red blood cells binds to oxygen?",
        answer: "HEMOGLOBIN",
        options: JSON.stringify(["INSULIN","HEMOGLOBIN","COLLAGEN","FIBRIN"]),
        type: 'multiple_choice',
        position: 13
      },
      {
        id: "qs-7-q14",
        set_id: "qs-7",
        prompt_text: "What connects muscles to bones?",
        answer: "TENDONS",
        options: JSON.stringify(["LIGAMENTS","TENDONS","CARTILAGE","NERVES"]),
        type: 'multiple_choice',
        position: 14
      },
      {
        id: "qs-7-q15",
        set_id: "qs-7",
        prompt_text: "What connects bones to other bones at joints?",
        answer: "LIGAMENTS",
        options: JSON.stringify(["TENDONS","LIGAMENTS","VEINS","MUSCLES"]),
        type: 'multiple_choice',
        position: 15
      },
    ],
  },
  {
    id: "qs-8",
    owner_id: "u-teacher-1",
    owner_name: "Mrs. Sarah Davis",
    title: "Plant Biology & Botany (15 Items)",
    description: "Deep dive into plant structures, photosynthesis, cell walls, xylem/phloem, pollination, and germination.",
    subject: "Science",
    grade_level: "Grade 3 - 8",
    is_public: true,
    tags: JSON.stringify(["science","botany","plants","photosynthesis","biology"]),
    created_at: '2026-08-01 08:00:00',
    updated_at: '2026-08-05 12:00:00',
    questions: [
      {
        id: "qs-8-q1",
        set_id: "qs-8",
        prompt_text: "What process do green plants use to convert sunlight into food energy?",
        answer: "PHOTOSYNTHESIS",
        options: JSON.stringify(["PHOTOSYNTHESIS","RESPIRATION","TRANSPIRATION","GERMINATION"]),
        type: 'multiple_choice',
        position: 1
      },
      {
        id: "qs-8-q2",
        set_id: "qs-8",
        prompt_text: "What green pigment in plant leaves absorbs sunlight?",
        answer: "CHLOROPHYLL",
        options: JSON.stringify(["CAROTENE","CHLOROPHYLL","MELANIN","XANTHOPHYLL"]),
        type: 'multiple_choice',
        position: 2
      },
      {
        id: "qs-8-q3",
        set_id: "qs-8",
        prompt_text: "Which plant organ absorbs water and minerals from the soil?",
        answer: "ROOTS",
        options: JSON.stringify(["LEAVES","STEM","ROOTS","FLOWERS"]),
        type: 'multiple_choice',
        position: 3
      },
      {
        id: "qs-8-q4",
        set_id: "qs-8",
        prompt_text: "What gas do plants absorb from the air for photosynthesis?",
        answer: "CARBON DIOXIDE",
        options: JSON.stringify(["OXYGEN","CARBON DIOXIDE","NITROGEN","ARGON"]),
        type: 'multiple_choice',
        position: 4
      },
      {
        id: "qs-8-q5",
        set_id: "qs-8",
        prompt_text: "What gas is released by plants as a byproduct of photosynthesis?",
        answer: "OXYGEN",
        options: JSON.stringify(["OXYGEN","CARBON DIOXIDE","METHANE","HYDROGEN"]),
        type: 'multiple_choice',
        position: 5
      },
      {
        id: "qs-8-q6",
        set_id: "qs-8",
        prompt_text: "What plant tissue transports water from roots to leaves?",
        answer: "XYLEM",
        options: JSON.stringify(["PHLOEM","XYLEM","EPIDERMIS","STOMATA"]),
        type: 'multiple_choice',
        position: 6
      },
      {
        id: "qs-8-q7",
        set_id: "qs-8",
        prompt_text: "What plant tissue transports synthesized sugars and nutrients?",
        answer: "PHLOEM",
        options: JSON.stringify(["XYLEM","PHLOEM","CAMBIUM","ROOT HAIR"]),
        type: 'multiple_choice',
        position: 7
      },
      {
        id: "qs-8-q8",
        set_id: "qs-8",
        prompt_text: "What are the microscopic pores on leaves that allow gas exchange?",
        answer: "STOMATA",
        options: JSON.stringify(["STOMATA","CHLOROPLASTS","CUTICLES","VASCULAR BUNDLES"]),
        type: 'multiple_choice',
        position: 8
      },
      {
        id: "qs-8-q9",
        set_id: "qs-8",
        prompt_text: "What organelle in plant cells carries out photosynthesis?",
        answer: "CHLOROPLAST",
        options: JSON.stringify(["MITOCHONDRIA","CHLOROPLAST","NUCLEUS","VACUOLE"]),
        type: 'multiple_choice',
        position: 9
      },
      {
        id: "qs-8-q10",
        set_id: "qs-8",
        prompt_text: "What rigid outer layer gives plant cells structural support?",
        answer: "CELL WALL",
        options: JSON.stringify(["CELL MEMBRANE","CELL WALL","CYTOSKELETON","CAPSULE"]),
        type: 'multiple_choice',
        position: 10
      },
      {
        id: "qs-8-q11",
        set_id: "qs-8",
        prompt_text: "What is the process of a seed sprouting into a young seedling?",
        answer: "GERMINATION",
        options: JSON.stringify(["POLLINATION","GERMINATION","FERTILIZATION","TRANSPIRATION"]),
        type: 'multiple_choice',
        position: 11
      },
      {
        id: "qs-8-q12",
        set_id: "qs-8",
        prompt_text: "Which male flower part produces pollen grains?",
        answer: "ANTHER",
        options: JSON.stringify(["STIGMA","ANTHER","PETAL","OVARY"]),
        type: 'multiple_choice',
        position: 12
      },
      {
        id: "qs-8-q13",
        set_id: "qs-8",
        prompt_text: "Which female flower part receives pollen during pollination?",
        answer: "STIGMA",
        options: JSON.stringify(["STIGMA","ANTHER","FILAMENT","SEPAL"]),
        type: 'multiple_choice',
        position: 13
      },
      {
        id: "qs-8-q14",
        set_id: "qs-8",
        prompt_text: "What process transfers pollen from anther to stigma?",
        answer: "POLLINATION",
        options: JSON.stringify(["GERMINATION","POLLINATION","PHOTOSYNTHESIS","ABSORPTION"]),
        type: 'multiple_choice',
        position: 14
      },
      {
        id: "qs-8-q15",
        set_id: "qs-8",
        prompt_text: "What part of the flower develops into a fruit after fertilization?",
        answer: "OVARY",
        options: JSON.stringify(["PETAL","OVARY","SEPAL","STIGMA"]),
        type: 'multiple_choice',
        position: 15
      },
    ],
  },
];

export const INITIAL_ASSIGNMENTS = [
  {
    id: 'asg-1',
    teacher_id: 'u-teacher-1',
    teacher_name: 'Mrs. Sarah Davis',
    class_id: 'cls-2b',
    class_name: 'Grade 3 - Room 2B',
    question_set_id: 'qs-1',
    question_set_title: 'Sight Words & Early Phonics',
    game_slug: 'wheel-spin',
    game_name: 'Wheel Spin',
    join_code: 'FUN-7890',
    due_date: '2026-08-10',
    rewards_enabled: true,
    created_at: '2026-07-28 08:00:00',
  },
  {
    id: 'asg-2',
    teacher_id: 'u-teacher-1',
    teacher_name: 'Mrs. Sarah Davis',
    class_id: 'cls-2b',
    class_name: 'Grade 3 - Room 2B',
    question_set_id: 'qs-2',
    question_set_title: 'Math Safari: Addition & Multiplication',
    game_slug: 'ship-battle',
    game_name: 'Ship Battle',
    join_code: 'MATH-4321',
    due_date: '2026-08-15',
    rewards_enabled: true,
    created_at: '2026-07-29 09:30:00',
  },
];

export const INITIAL_ATTEMPTS = [
  {
    id: 'att-1',
    assignment_id: 'asg-1',
    student_id: 'u-student-1',
    student_name: 'Leo Martinez',
    question_set_id: 'qs-1',
    question_set_title: 'Sight Words & Early Phonics',
    game_slug: 'wheel-spin',
    score: 450,
    accuracy: 100,
    total_questions: 5,
    correct_count: 5,
    completed_at: '2026-07-30 14:20:00',
    answers: [
      { question_id: 'q1-1', question_prompt: 'Which word means "at the present time"?', student_answer: 'NOW', correct_answer: 'NOW', is_correct: true },
      { question_id: 'q1-2', question_prompt: 'What is the opposite of "BEFORE"?', student_answer: 'AFTER', correct_answer: 'AFTER', is_correct: true },
      { question_id: 'q1-3', question_prompt: 'Read and spell the word for a shining star.', student_answer: 'BRIGHT', correct_answer: 'BRIGHT', is_correct: true },
      { question_id: 'q1-4', question_prompt: 'The birds fly high in the ______.', student_answer: 'SKY', correct_answer: 'SKY', is_correct: true },
      { question_id: 'q1-5', question_prompt: 'Which word rhymes with "BEACH"?', student_answer: 'PEACH', correct_answer: 'PEACH', is_correct: true },
    ],
  },
  {
    id: 'att-2',
    assignment_id: 'asg-1',
    student_id: 'u-student-2',
    student_name: 'Sophia Chen',
    question_set_id: 'qs-1',
    question_set_title: 'Sight Words & Early Phonics',
    game_slug: 'wheel-spin',
    score: 360,
    accuracy: 80,
    total_questions: 5,
    correct_count: 4,
    completed_at: '2026-07-31 09:10:00',
    answers: [
      { question_id: 'q1-1', question_prompt: 'Which word means "at the present time"?', student_answer: 'NOW', correct_answer: 'NOW', is_correct: true },
      { question_id: 'q1-2', question_prompt: 'What is the opposite of "BEFORE"?', student_answer: 'UNDER', correct_answer: 'AFTER', is_correct: false },
      { question_id: 'q1-3', question_prompt: 'Read and spell the word for a shining star.', student_answer: 'BRIGHT', correct_answer: 'BRIGHT', is_correct: true },
      { question_id: 'q1-4', question_prompt: 'The birds fly high in the ______.', student_answer: 'SKY', correct_answer: 'SKY', is_correct: true },
      { question_id: 'q1-5', question_prompt: 'Which word rhymes with "BEACH"?', student_answer: 'PEACH', correct_answer: 'PEACH', is_correct: true },
    ],
  },
];

export const INITIAL_STICKERS = [
  { id: 'stk-1', name: 'Cosmic Dino', rarity: 'Common', category: 'Space', emoji: '🦖', description: 'Roars through the galaxy!' },
  { id: 'stk-2', name: 'Super Star', rarity: 'Common', category: 'Classroom', emoji: '⭐', description: 'Shines bright for good work!' },
  { id: 'stk-3', name: 'Wizard Owl', rarity: 'Rare', category: 'Magic', emoji: '🦉', description: 'Wise master of spell casting.' },
  { id: 'stk-4', name: 'Golden Trophy', rarity: 'Legendary', category: 'Achievements', emoji: '🏆', description: 'Awarded to top champions!' },
  { id: 'stk-5', name: 'Rocket Ship', rarity: 'Rare', category: 'Space', emoji: '🚀', description: 'Blasts off towards success!' },
  { id: 'stk-6', name: 'Brainy Fox', rarity: 'Common', category: 'Animals', emoji: '🦊', description: 'Quick-thinking puzzle solver.' },
  { id: 'stk-7', name: 'Sparkle Unicorn', rarity: 'Epic', category: 'Fantasy', emoji: '🦄', description: 'Magical powers of learning.' },
  { id: 'stk-8', name: 'Robo Pal', rarity: 'Rare', category: 'Sci-Fi', emoji: '🤖', description: 'Beep boop! 100% correct answers.' },
  { id: 'stk-9', name: 'Ocean Dolphin', rarity: 'Common', category: 'Ocean', emoji: '🐬', description: 'Dives deep into knowledge.' },
  { id: 'stk-10', name: 'Diamond Shield', rarity: 'Legendary', category: 'Power', emoji: '💎', description: 'Unstoppable streak defense!' },
  { id: 'stk-11', name: 'Magic Cauldron', rarity: 'Epic', category: 'Magic', emoji: '🧪', description: 'Brewing genius ideas.' },
  { id: 'stk-12', name: 'Pirate Captain', rarity: 'Rare', category: 'Adventure', emoji: '🏴‍☠️', description: 'Sails the high seas of math!' },
];

export const INITIAL_ROSTER = [
  { id: 's1', name: 'Leo Martinez', avatar: '🦁', stars: 12, points: 450 },
  { id: 's2', name: 'Sophia Chen', avatar: '🐼', stars: 15, points: 520 },
  { id: 's3', name: 'Marcus Vance', avatar: '🚀', stars: 9, points: 310 },
  { id: 's4', name: 'Emma Watson', avatar: '🦄', stars: 18, points: 680 },
  { id: 's5', name: 'Jayden Brooks', avatar: '🦖', stars: 14, points: 490 },
  { id: 's6', name: 'Ava Patel', avatar: '🦊', stars: 11, points: 390 },
  { id: 's7', name: 'Noah Miller', avatar: '🤖', stars: 16, points: 580 },
  { id: 's8', name: 'Mia Taylor', avatar: '🦉', stars: 13, points: 440 },
];

export const INITIAL_REWARDS = [
  {
    student_id: 'u-student-1',
    points: 4500,
    tickets_earned: 2500,
    unlocked_sticker_ids: JSON.stringify(['stk-1', 'stk-2']),
  },
];